Repository BoooostUp/carone, pull requests merged in 2024-04, with the labels that each got.

#19 [컴포넌트] Root 페이지 수정, 로고와 인재채용 버튼 구현
  src/components/RecruitButton.jsx
  src/pages/Root.jsx
Labels: Feat, Refactor

#24 [컴포넌트] WelcomeBox 구현
  src/components/Main/WelcomeBox.jsx
  src/constants/WELCOME_BOX_CONTENTS.js
  src/pages/Home.jsx
Labels: Feat

#28 [컴포넌트] Map 구현
  src/assets/images/map/CARONE2.webp
  src/assets/images/map/CE_CARONE_SG.webp
  src/assets/images/map/TOTAL_SI.webp
  src/components/Main/Map.jsx
  src/constants/MAP_CONTENTS.js
Labels: Feat

#30 [컴포넌트] QnA button 구현
  src/assets/icons/questionMark.svg
  src/components/Main/QnAButton.jsx
Labels: Feat

#31 [컴포넌트] 회사명 변경에 따른 배경색 적용 안 되는 문제 수정
  src/constants/ROOT.js
Labels: Fix

#29 [컴포넌트] Subcategory Bar
  src/Router.jsx
  src/components/Main/SubCategoryBar.jsx
Labels: Feat, Fix

#34 [컴포넌트] 텍스트 드래그 방지
  src/styles/GlobalStyle.js
Labels: Refactor

#36 [컴포넌트] Footer 가 받는 argument changed
  src/assets/logo.svg
  src/components/Footer/Footer.jsx
  src/components/Footer/FooterExample.jsx
  src/constants/FOOTER_CONTENTS.js
Labels: Fix

#41 [컴포넌트] Router파일 삭제
  src/Router.jsx
Labels: Fix

#37 [컴포넌트] BNB state 관리 + props로 company 이름으로 변경
  src/App.jsx
  src/components/Footer/Footer.jsx
  src/components/Main/BNB/Bnb.jsx
  src/components/Main/BNB/BnbButton.jsx
  src/components/Main/BNB/BnbTestPage.jsx
  src/pages/Carone/Carone.jsx
  src/pages/Carone2/Carone2.jsx
  src/pages/Ce/Ce.jsx
  src/pages/Home/Home.jsx
  src/pages/Sg/Sg.jsx
  src/pages/Si/Si.jsx
  src/pages/Total/Total.jsx
  src/pages/Total2/Total2.jsx
Labels: Fix

#44 [컴포넌트] QnA Modal UI 구현
  src/assets/icons/close.png
  src/components/Main/QnAButton.jsx
  src/components/Main/QnAModal.jsx
Labels: Feat

#45 [컴포넌트] Hero컴포넌트 완성 및 각 페이지에 적용
  src/assets/images/hero/caroneCars.jpg
  src/components/Main/Hero.jsx
  src/constants/HERO_CONTENTS.js
  src/hooks/useHeroAttribute.jsx
  src/pages/Carone/Carone.jsx
  src/pages/Carone2/Carone2.jsx
  src/pages/Ce/Ce.jsx
  src/pages/Home/Home.jsx
  src/pages/Sg/Sg.jsx
  src/pages/Si/Si.jsx
  src/pages/Total/Total.jsx
  src/pages/Total2/Total2.jsx
Labels: Feat

#46 [라우터] 카테고리 레이아웃 적용 및 카테고리 수정
  src/Router/Carone2Routes.jsx
  src/Router/CaroneRoutes.jsx
  src/Router/CeRoutes.jsx
  src/Router/SgRoutes.jsx
  src/Router/SiRoutes.jsx
  src/Router/Total2Routes.jsx
  src/Router/TotalRoutes.jsx
  src/components/Header/Lnb.jsx
  src/components/Main/CategoryBar.jsx
  src/constants/LNB_CONTENTS.js
  src/pages/Carone/Business/CaroneBusinessLayout.jsx
  src/pages/Carone/Info/CaroneInfoLayout.jsx
  src/pages/Carone2/Business/Carone2BusinessLayout.jsx
  src/pages/Carone2/Info/Carone2InfoLayout.jsx
  src/pages/Ce/Business/CeBusinessLayout.jsx
  src/pages/Ce/Info/CeInfoLayout.jsx
  src/pages/Sg/Business/SgBusinessLayout.jsx
  src/pages/Sg/Info/SgInfoLayout.jsx
  src/pages/Si/Business/SiBusinessLayout.jsx
  src/pages/Si/Info/SiInfoLayout.jsx
  src/pages/Total/Business/TotalBusinessLayout.jsx
  src/pages/Total/Info/TotalInfoLayout.jsx
  src/pages/Total2/Business/Total2BusinessLayout.jsx
  src/pages/Total2/Info/Total2InfoLayout.jsx
Labels: Feat

#48 [컴포넌트] QnA Button 화면에 고정
  src/pages/Carone/Carone.jsx
  src/pages/Carone2/Carone2.jsx
  src/pages/Ce/Ce.jsx
  src/pages/Home/Home.jsx
  src/pages/Sg/Sg.jsx
  src/pages/Si/Si.jsx
  src/pages/Total/Total.jsx
  src/pages/Total2/Total2.jsx
Labels: Feat

#50 [컴포넌트] LNB 보여질 때 밑의 컨텐츠 밀리지 않도록 수정 및 애니메이션 추가
  src/components/Header/Lnb.jsx
Labels: Refactor

#51 [컴포넌트] Hero 모바일 기능 추가
  src/components/Main/Hero.jsx
Labels: Feat

#47 [컴포넌트] BNB높이수정, 작은에러 수정
  src/components/Main/BNB/Bnb.jsx
  src/components/Main/BNB/BnbButton.jsx
  src/pages/Carone/Carone.jsx
  src/pages/Carone2/Carone2.jsx
  src/pages/Ce/Ce.jsx
  src/pages/Home/Home.jsx
  src/pages/Sg/Sg.jsx
  src/pages/Si/Si.jsx
  src/pages/Total/Total.jsx
  src/pages/Total2/Total2.jsx
Labels: Fix

#53 [컴포넌트] LNB 스크롤 시 고정되도록 수정
  src/components/Header/Lnb.jsx
Labels: Fix

#54 [Feat] Add articles
  src/components/Main/QnAButton.jsx
  src/pages/Carone/Carone.jsx
  src/pages/Carone2/Carone2.jsx
  src/pages/Ce/Ce.jsx
  src/pages/Home/Home.jsx
  src/pages/Home/HomeMain.jsx
  src/pages/Sg/Sg.jsx
  src/pages/Si/Si.jsx
  src/pages/Total/Total.jsx
  src/pages/Total2/Total2.jsx
Labels: Feat, Fix

#55 Hero 어두운 화면 위치 조정
  src/components/Main/Hero.jsx
Labels: Fix

#57 [컴포넌트] LNB 컨테이너에 z-index 추가
  src/components/Header/Lnb.jsx
Labels: Fix

#59 [컴포넌트] WelcomeBox 적용
  src/components/Main/Hero.jsx
  src/components/Main/WelcomeBox.jsx
Labels: Feat, Fix

#58 ✨ Feat: Add certification feature on carone test1
  src/Router/Router.jsx
  src/components/Certification/CERTIFICATIONS.js
  src/components/Certification/Certificate.jsx
  src/components/Certification/CertificateModal.jsx
  src/components/Certification/CertificationComponent.jsx
  src/components/Main/SubCategoryBar.jsx
  src/pages/Carone/CaroneLicenses.jsx
Labels: Feat, Test

#60 [컴포넌트] Root페이지 모바일 버전 구현
  src/components/RecruitButton.jsx
  src/pages/Root.jsx
Labels: Feat, Refactor

#61 ✨ Feat: Carone Business Layout 작업 및 내용 추가
  src/assets/images/carone/process.png
  src/assets/images/carone/고철운반.png
  src/assets/images/carone/사업내용.png
  src/assets/images/carone/영업대상폐기물.png
  src/assets/images/carone/취급품목.png
  src/components/Main/SubCategoryBar.jsx
  src/pages/Carone/Business/CaroneBusinessAbout.jsx
  src/pages/Carone/Business/CaroneBusinessLayout.jsx
  src/pages/Carone/Business/CaroneBusinessProcess.jsx
  src/pages/Carone/Business/CaroneBusinessWaste.jsx
Labels: Feat

#62 [컴포넌트] 배포 시 이미지가 렌더링 되지 않는 현상 수정
  src/constants/ROOT.js
  src/pages/Root.jsx
Labels: Fix

#64 [카원] 카원 1공장 회사소개 페이지 구현
  src/assets/images/carone/caroneInfoCeo.webp
  src/assets/images/carone/caroneInfoHistory.webp
  src/assets/images/ce/business_partner1.png
  src/assets/images/ce/business_partner2.png
  src/assets/images/ce/business_partner3.png
  src/assets/images/ce/business_partner4.png
  src/assets/images/ce/business_partner5.png
  src/assets/images/ce/business_partner6.png
  src/assets/images/sg/business_partner1.png
  src/components/Main/BusinessPartner.jsx
  src/components/Main/QnAModal.jsx
  src/constants/BUSINESS_PARTNER_CONTENTS.js
  src/constants/MAIN_ARTICLE_CONTENTS.js
  src/pages/Carone/Info/CaroneInfoBusinessPartner.jsx
  src/pages/Carone/Info/CaroneInfoCeo.jsx
  src/pages/Carone/Info/CaroneInfoHistory.jsx
  src/pages/Carone/Info/CaroneInfoLayout.jsx
  src/pages/Carone/Info/CaroneInfoLocation.jsx
Labels: Feat

#65 [컴포넌트] 이미지 파일 Import로 불러오도록 수정 및 MainArticle 위치 변경
  src/constants/INTRO_CONTENT_CONTENTS.js
  src/constants/MAIN_ARTICLE_CONTENTS.js
  src/pages/Home/HomeBusiness.jsx
  src/pages/Home/HomeMain.jsx
Labels: Fix

#63 [컴포넌트] WelcomeBox가 main 이외의 페이지이서 보이는 현상 수정
  src/components/Main/Hero.jsx
  src/components/Main/WelcomeBox.jsx
  src/constants/WELCOME_BOX_CONTENTS.js
  src/hooks/useHeroAttribute.jsx
  src/pages/Carone/Carone.jsx
  src/pages/Carone2/Carone2.jsx
  src/pages/Ce/Ce.jsx
  src/pages/Home/Home.jsx
  src/pages/Sg/Sg.jsx
  src/pages/Si/Si.jsx
  src/pages/Total/Total.jsx
  src/pages/Total2/Total2.jsx
Labels: Fix

#66 Gnb 마우스 오버 수정 및 카테고리바 모바일 반응형 작업
  src/components/Header/Gnb.jsx
  src/components/Main/CategoryBar.jsx
  src/components/Main/SubCategoryBar.jsx
  src/pages/Carone/Business/CaroneBusinessLayout.jsx
Labels: Feat, Fix

#67 [컴포넌트] 모바일 사이즈일 때 이미지, 텍스트 가로 사이즈 수정
  src/components/Main/IntroContent.jsx
  src/components/Main/MainArticle.jsx
Labels: Fix

#69 [Fix] 회사 이름 수정
  src/constants/GNB_CONTENTS.js
  src/constants/MAP_CONTENTS.js
Labels: Fix

#70 [Page] Business Layout 및 사업내용 페이지 회사별 작업
  src/assets/images/carone2/businessAbout.png
  src/assets/images/carone2/businessProcess.png
  src/assets/images/carone2/businessWaste.png
  src/assets/images/ce/businessAbout.png
  src/assets/images/ce/businessRegistration.png
  src/assets/images/ce/businessWaste.png
  src/assets/images/sg/businessFlowchart.png
  src/assets/images/sg/businessWaste.png
  src/assets/images/sg/이온정제유.png
  src/assets/images/sg/재생연료유.png
  src/assets/images/sg/재생연료유_공정.png
  src/assets/images/si/businessCleaning.png
  src/assets/images/si/businessDredging.png
  src/assets/images/si/businessPipe.png
  src/assets/images/total/businessAbout copy.png
  src/assets/images/total/businessAbout.png
  src/assets/images/total/businessProcess.png
  src/assets/images/total/businessWaste.png
  src/assets/images/total2/businessAbout.png
  src/assets/images/total2/businessProcess.png
  src/assets/images/total2/businessWaste.png
  src/components/Main/SubCategoryBar.jsx
  src/pages/Carone/Business/CaroneBusinessLayout.jsx
  src/pages/Carone2/Business/Carone2BusinessAbout.jsx
  src/pages/Carone2/Business/Carone2BusinessLayout.jsx
  src/pages/Carone2/Business/Carone2BusinessProcess.jsx
  src/pages/Carone2/Business/Carone2BusinessWaste.jsx
  src/pages/Ce/Business/CeBusinessAbout.jsx
  src/pages/Ce/Business/CeBusinessLayout.jsx
  src/pages/Ce/Business/CeBusinessRegistration.jsx
  src/pages/Ce/Business/CeBusinessWaste.jsx
  src/pages/Sg/Business/SgBusinessAbout.jsx
  src/pages/Sg/Business/SgBusinessFlowchart.jsx
  src/pages/Sg/Business/SgBusinessLayout.jsx
  src/pages/Sg/Business/SgBusinessWaste.jsx
  src/pages/Si/Business/SiBusinessCleaning.jsx
  src/pages/Si/Business/SiBusinessDredging.jsx
  src/pages/Si/Business/SiBusinessLayout.jsx
  src/pages/Si/Business/SiBusinessPipe.jsx
  src/pages/Total/Business/TotalBusinessAbout.jsx
  src/pages/Total/Business/TotalBusinessLayout.jsx
  src/pages/Total/Business/TotalBusinessProcess.jsx
  src/pages/Total/Business/TotalBusinessWaste.jsx
  src/pages/Total2/Business/Total2BusinessAbout.jsx
  src/pages/Total2/Business/Total2BusinessLayout.jsx
  src/pages/Total2/Business/Total2BusinessProcess.jsx
  src/pages/Total2/Business/Total2BusinessWaste.jsx
Labels: Feat

#71 [카원/자동차환경/에스지산업/세명인텍/토탈] 보유 설비 페이지 구현
  src/assets/images/facilities/carone1Facilities.png
  src/assets/images/facilities/ceFacilities.png
  src/assets/images/facilities/sgFacilities.png
  src/assets/images/facilities/siFacilities.png
  src/assets/images/facilities/total1Facilities.png
  src/assets/images/facilities/total2Facilities.png
  src/pages/Carone/CaroneFacilities.jsx
  src/pages/Carone2/Carone2Facilities.jsx
  src/pages/Ce/CeFacilities.jsx
  src/pages/Sg/SgFacilities.jsx
  src/pages/Si/SiFacilities.jsx
  src/pages/Total/TotalFacilities.jsx
  src/pages/Total2/Total2Facilities.jsx
Labels: Feat

#68 [카원/자동차환경/에스지산업/세명인텍/토탈] 회사소개 페이지 구현
  src/assets/images/ce/ceInfoCeo.webp
  src/assets/images/ce/ceInfoHistory.webp
  src/assets/images/sg/sgInfoCeo.webp
  src/assets/images/sg/sgInfoHistory.webp
  src/assets/images/total/totalInfoCeo.jpg
  src/assets/images/total/totalInfoHistory.jpg
  src/assets/images/total2/total2InfoHistory.jpg
  src/pages/Carone/Info/CaroneInfoBusinessPartner.jsx
  src/pages/Carone/Info/CaroneInfoLayout.jsx
  src/pages/Carone/Info/CaroneInfoLocation.jsx
  src/pages/Carone2/Info/Carone2InfoBusinessPartner.jsx
  src/pages/Carone2/Info/Carone2InfoCeo.jsx
  src/pages/Carone2/Info/Carone2InfoHistory.jsx
  src/pages/Carone2/Info/Carone2InfoLayout.jsx
  src/pages/Carone2/Info/Carone2InfoLocation.jsx
  src/pages/Ce/Info/CeInfoBusinessPartner.jsx
  src/pages/Ce/Info/CeInfoCeo.jsx
  src/pages/Ce/Info/CeInfoHistory.jsx
  src/pages/Ce/Info/CeInfoLayout.jsx
  src/pages/Ce/Info/CeInfoLocation.jsx
  src/pages/Sg/Info/SgInfoBusinessPartner.jsx
  src/pages/Sg/Info/SgInfoCeo.jsx
  src/pages/Sg/Info/SgInfoHistory.jsx
  src/pages/Sg/Info/SgInfoLayout.jsx
  src/pages/Sg/Info/SgInfoLocation.jsx
  src/pages/Si/Info/SiInfoBusinessPartner.jsx
  src/pages/Si/Info/SiInfoCeo.jsx
  src/pages/Si/Info/SiInfoHistory.jsx
  src/pages/Si/Info/SiInfoLayout.jsx
  src/pages/Si/Info/SiInfoLocation.jsx
  src/pages/Total/Info/TotalInfoBusinessPartner.jsx
  src/pages/Total/Info/TotalInfoCeo.jsx
  src/pages/Total/Info/TotalInfoHistory.jsx
  src/pages/Total/Info/TotalInfoLayout.jsx
  src/pages/Total/Info/TotalInfoLocation.jsx
  src/pages/Total2/Info/Total2InfoBusinessPartner.jsx
  src/pages/Total2/Info/Total2InfoCeo.jsx
  src/pages/Total2/Info/Total2InfoHistory.jsx
  src/pages/Total2/Info/Total2InfoLayout.jsx
  src/pages/Total2/Info/Total2InfoLocation.jsx
Labels: Feat

#73 [컴포넌트] 웰컴박스 텍스트 투명도 수정
  src/components/Main/WelcomeBox.jsx
Labels: Fix

#76 [FIX] 💚 Fix: Fix home footer UI
  src/components/Footer/Footer.jsx
Labels: Fix

#75 [컴포넌트] 텍스트 양옆에 padding 추가
  src/components/Main/MainArticle.jsx
Labels: Fix

#78 [Add UI] ⚡️ Feat: Added main page for each companies
  src/pages/Carone/CaroneMain.jsx
  src/pages/Carone2/Carone2Main.jsx
  src/pages/Ce/CeMain.jsx
  src/pages/Sg/SgMain.jsx
  src/pages/Si/SiMain.jsx
  src/pages/Total/TotalMain.jsx
  src/pages/Total2/Total2Main.jsx
Labels: Feat

#81 [Page] home에 인사말, 오시는 길 페이지 구현, Map 수정
  src/assets/images/home/ceo.png
  src/components/Main/Map.jsx
  src/pages/Home/HomeCeo.jsx
  src/pages/Home/HomeLocation.jsx
Labels: Feat

#79 [컴포넌트] QnA 모달 사이즈 수정
  src/components/Main/QnAModal.jsx
  src/pages/Carone/Info/CaroneInfoBusinessPartner.jsx
  src/pages/Carone2/Info/Carone2InfoBusinessPartner.jsx
  src/pages/Ce/Info/CeInfoBusinessPartner.jsx
  src/pages/Sg/Info/SgInfoBusinessPartner.jsx
  src/pages/Si/Info/SiInfoBusinessPartner.jsx
  src/pages/Total/Info/TotalInfoBusinessPartner.jsx
  src/pages/Total2/Info/Total2InfoBusinessPartner.jsx
Labels: Fix

#80 [컴포넌트] 카원, 토탈 1공장에서 홈 페이지 배경색 적용 안되는 부분 수정
  src/pages/Carone/CaroneMain.jsx
  src/pages/Total/TotalMain.jsx
Labels: Fix

#82 [FIX] 🩹 Fix: fix minor issues
  src/components/Certification/CertificateModal.jsx
  src/components/Main/SubCategoryBar.jsx
  src/constants/FOOTER_CONTENTS.js
Labels: Fix

#83 [컴포넌트] 인재 채용 페이지
  src/Router/HomeRoutes.jsx
  src/assets/images/home/recruitProcess.png
  src/constants/GNB_CONTENTS.js
  src/constants/LNB_CONTENTS.js
  src/main.jsx
  src/pages/Home/HomeRecruit.jsx
  src/pages/Home/HomeRecruit/HomeRecruitApply.jsx
  src/pages/Home/HomeRecruit/HomeRecruitLayout.jsx
  src/pages/Home/HomeRecruit/HomeRecruitProcess.jsx
  src/pages/Root.jsx
Labels: Feat

#84 [컴포넌트] 인재 채용 글자 수정
  src/pages/Home/HomeRecruit/HomeRecruitApply.jsx
Labels: Fix
