Repository BoooostUp/carone, pull requests merged in 2024-09, with the labels that each got.

#116 [컴포넌트] IntroContent UI 업데이트
  src/components/Main/IntroContent.jsx
Labels: Refactor

#117 [컴포넌트] company carousel 제작
  src/components/Main/CompanyCarousel.jsx
  src/components/Main/IntroContent.jsx
  src/pages/Home/Home.jsx
Labels: Feat

#118 Feat: main 상단 소개, 하단 거래처 UI 구현
  package-lock.json
  package.json
  src/assets/images/home/main_info.png
  src/assets/images/home/main_info2.png
  src/assets/images/home/partner_background.jpg
  src/components/Main/IntroContent.jsx
  src/components/Main/MainInfo.jsx
  src/components/Main/Partners/Partners.jsx
  src/constants/MAIN_PARTNER_CONTENTS.js
  src/pages/Home/HomeMain.jsx
Labels: Feat

#120 [컴포넌트] IntroContent 애니메이션 작동 수정
  package-lock.json
  src/components/Main/IntroContent.jsx
Labels: Fix
