Repository BoooostUp/carone, pull requests merged in 2024-03, with the labels that each got.

#5 ♻️ refactor: import순서 제어를 위한 lint 수정
  package-lock.json
  package.json
Labels: Refactor

#7 ✨ Feat: Added DOM-Basic router setting
  package-lock.json
  package.json
  src/App.jsx
  src/Router.jsx
  src/pages/Carone.jsx
  src/pages/Ce.jsx
  src/pages/Home.jsx
  src/pages/Layout.jsx
  src/pages/Root.jsx
  src/pages/Sg.jsx
  src/pages/Si.jsx
  src/pages/Total.jsx
Labels: Feat

#3 🌱 Feat: Add media query type script file
  src/styles/utils/mediaQuery.ts
Labels: Feat

#8 ✨ Feat: Add Component Example Folders
  src/components/Footer/FooterExample.jsx
  src/components/Header/HeaderExample.jsx
  src/components/Main/MainExample.jsx
Labels: Feat

#13 [초기세팅] eslint rules에 option 추가
  .eslintrc.cjs
Labels: Fix

#9 [컴포넌트] GNB 구현
  index.html
  src/assets/icons/Logo.svg
  src/components/Header/GNB.jsx
  src/constants/GNB_CONTENTS.js
  src/styles/theme.js
Labels: Feat

#10 [컴포넌트] LNB UI 구현
  src/components/Header/LNB/LNB.jsx
  src/constants/LNB_CONTENTS.js
Labels: Feat

#12 [컴포넌트] Root 구현
  src/assets/images/root/carone.png
  src/assets/images/root/ce.png
  src/assets/images/root/home.png
  src/assets/images/root/sg.png
  src/assets/images/root/total.png
  src/constants/ROOT.js
  src/pages/Root.jsx
Labels: Feat

#14 [컴포넌트] Footer 구현
  src/Router.jsx
  src/assets/logo.svg
  src/components/Footer/FOOTER_CONTENTS.js
  src/components/Footer/Footer.jsx
  src/components/Footer/FooterExample.jsx
Labels: Feat

#15 [컴포넌트] MainArticle 구현
  src/assets/images/mainArticle/carone.webp
  src/assets/images/mainArticle/ce.webp
  src/assets/images/mainArticle/sg.webp
  src/assets/images/mainArticle/si.webp
  src/assets/images/mainArticle/total.webp
  src/components/Main/MainArticle.jsx
  src/constants/MAIN_ARTICLE_CONTENTS.js
Labels: Feat

#11 [컴포넌트] BNB 구현
  package-lock.json
  package.json
  src/components/Main/BNB/Bnb.jsx
  src/components/Main/BNB/BnbButton.jsx
  src/components/Main/BNB/BnbTestPage.jsx
  src/pages/Carone.jsx
Labels: Feat

#16 [컴포넌트] Footer Fix
  src/components/Footer/FooterExample.jsx
  src/constants/FOOTER_CONTENTS.js
Labels: Fix

#18 [컴포넌트] IntroContent 구현
  src/assets/images/introContent/IntroContent1.webp
  src/assets/images/introContent/IntroContent2.webp
  src/assets/images/introContent/IntroContent3.webp
  src/assets/images/introContent/IntroContent4.webp
  src/components/Main/IntroContent.jsx
  src/constants/INTRO_CONTENT_CONTENTS.js
Labels: Feat

#20 [초기세팅] theme의 회사 이름 대문자로 변경
  src/styles/theme.js
Labels: Fix

#27 [컴포넌트] LNB 폴더 삭제 및 상수 불러올 때 toLowerCase 되지 않도록 변경
  src/components/Header/LNB.jsx
Labels: Fix

#26 [컴포넌트] 상수 객체 key 이름 수정
  src/components/Main/IntroContent.jsx
  src/constants/INTRO_CONTENT_CONTENTS.js
Labels: Fix

#25 [컴포넌트] 상수 객체 key, value 이름 수정 및 불러올 때 대문자로 불러오도록 수정
  src/components/Main/MainArticle.jsx
  src/constants/MAIN_ARTICLE_CONTENTS.js
Labels: Fix

#21 [컴포넌트] BNB constant 수정 BNB
  src/Router.jsx
  src/components/Main/BNB/Bnb.jsx
  src/components/Main/BNB/BnbButton.jsx
  src/pages/Layout.jsx
Labels: Fix

#17 [컴포넌트] Certification Modal
  src/Router.jsx
  src/assets/icons/lens.svg
  src/assets/images/certificates/certificate1.svg
  src/assets/images/certificates/certificate2.svg
  src/components/Certification/CERTIFICATIONS.js
  src/components/Certification/Certificate.jsx
  src/components/Certification/CertificateModal.jsx
  src/components/Certification/CertificationComponent.jsx
Labels: Feat

#23 [컴포넌트] 카테고리바 구현
  src/components/Main/CategoryBar.jsx
  src/constants/LNB_CONTENTS.js
Labels: Feat
