Repository BoooostUp/carone, pull requests merged in 2024-05, with the labels that each got.

#92 [CONE-46] CE, SG 메인아티클 내용 추가, BNB 버튼 클릭시 페이지 상단 이동
  index.html
  public/favicon.svg
  src/assets/images/ce/main1.png
  src/assets/images/ce/main2.png
  src/assets/images/ce/main3.png
  src/assets/images/ce/main4.png
  src/assets/images/sg/main1.png
  src/assets/images/sg/main2.png
  src/assets/images/sg/main3.png
  src/assets/images/sg/main4.png
  src/components/Main/BNB/Bnb.jsx
  src/constants/GNB_CONTENTS.js
  src/constants/MAIN_ARTICLE_CONTENTS.js
  src/constants/MAP_CONTENTS.js
  src/constants/ROOT.js
  src/pages/Ce/CeFacilities.jsx
Labels: Refactor

#94 [CONE-47] 🎨 Change BNB mobile size
  src/components/Main/BNB/BnbButton.jsx
Labels: Fix

#95 [CONE-48] total1, total2 메인 아티클 스크롤바 디자인 수정
  src/assets/images/total/total_factory.webp
  src/constants/MAIN_ARTICLE_CONTENTS.js
  src/styles/GlobalStyle.js
Labels: Feat, Fix, Refactor

#93 [CONE-46] 🎨 UI updated
  src/assets/images/dashboard/deal.gif
  src/assets/images/dashboard/facility.gif
  src/assets/images/dashboard/recycle.gif
  src/assets/images/dashboard/trash.gif
  src/assets/images/mainArticle/si.webp
  src/components/Main/DashBoard.jsx
  src/components/Main/IntroContent.jsx
  src/constants/GNB_CONTENTS.js
  src/constants/ROOT.js
  src/pages/Home/Home.jsx
Labels: Feat

#96 [CONE-49] carone1, 2 메인 아티클 이미지, 텍스트 추가 및 주요 거래처 회사별 로고 추가
  src/assets/images/carone/about1.webp
  src/assets/images/carone/about2.webp
  src/assets/images/carone/about3.webp
  src/assets/images/carone/business_partner1.webp
  src/assets/images/carone/business_partner2.webp
  src/assets/images/carone/business_partner3.webp
  src/assets/images/carone/business_partner4.webp
  src/assets/images/carone/business_partner5.webp
  src/assets/images/carone/business_partner6.webp
  src/assets/images/carone/business_partner7.webp
  src/assets/images/carone/business_partner8.webp
  src/assets/images/carone/main1.webp
  src/assets/images/carone/main2.webp
  src/assets/images/carone/main3.webp
  src/assets/images/carone/main4.webp
  src/assets/images/carone/waste.webp
  src/assets/images/carone/고철운반.png
  src/assets/images/carone/사업내용.png
  src/assets/images/carone/영업대상폐기물.png
  src/assets/images/carone/취급품목.png
  src/assets/images/carone2/business_partner1.webp
  src/assets/images/carone2/business_partner2.webp
  src/assets/images/carone2/business_partner3.webp
  src/assets/images/carone2/business_partner4.webp
  src/assets/images/carone2/business_partner5.webp
  src/assets/images/carone2/business_partner6.webp
  src/assets/images/carone2/business_partner7.webp
  src/assets/images/carone2/main1.webp
  src/assets/images/carone2/main2.webp
  src/assets/images/carone2/main3.webp
  src/assets/images/carone2/main4.webp
  src/components/Main/SubCategoryBar.jsx
  src/constants/BUSINESS_PARTNER_CONTENTS.js
  src/constants/MAIN_ARTICLE_CONTENTS.js
  src/pages/Carone/Business/CaroneBusinessWaste.jsx
Labels: Feat

#100 [CONE-50] welcomebox 크기, 글자 수정
  src/components/Main/WelcomeBox.jsx
  src/constants/WELCOME_BOX_CONTENTS.js
Labels: Refactor

#99 [CONE-49]👷 UI Update
  src/assets/images/carone/main1.webp
  src/assets/images/carone/main2.webp
  src/assets/images/carone/main3.webp
  src/assets/images/carone/main4.webp
  src/assets/images/ce/main1.webp
  src/assets/images/ce/main4.webp
  src/assets/images/mainArticle/total.webp
  src/assets/images/total/main1.webp
  src/assets/images/total/main2.webp
  src/assets/images/total/main3.webp
  src/assets/images/total/main4.webp
  src/assets/images/total2/main1.webp
  src/assets/images/total2/main3.webp
  src/assets/images/total2/main4.webp
  src/components/Certification/CERTIFICATIONS.js
  src/constants/MAIN_ARTICLE_CONTENTS.js
  src/pages/Si/SiLicenses/SiLicenses.jsx
Labels: Feat, Fix

#102 [CONE-51] 토탈1, 2공장 주요 거래처 이미지 적용
  src/assets/images/total/business_partner1.webp
  src/assets/images/total/business_partner2.webp
  src/assets/images/total/business_partner3.webp
  src/assets/images/total/business_partner4.webp
  src/assets/images/total/business_partner5.webp
  src/assets/images/total/business_partner6.webp
  src/assets/images/total/business_partner7.webp
  src/assets/images/total/business_partner8.webp
  src/assets/images/total/business_partner9.webp
  src/assets/images/total2/business_partner1.webp
  src/assets/images/total2/business_partner2.webp
  src/assets/images/total2/business_partner3.webp
  src/assets/images/total2/business_partner4.webp
  src/assets/images/total2/business_partner5.webp
  src/assets/images/total2/business_partner6.webp
  src/assets/images/total2/business_partner7.webp
  src/components/Main/BusinessPartner.jsx
  src/constants/BUSINESS_PARTNER_CONTENTS.js
Labels: Feat

#103 [CONE-52] 주요 거래처 이미지 비율 수정, 세명인텍 주요 거래처 이미지 추가
  src/assets/images/si/business_partner1.webp
  src/assets/images/si/business_partner2.webp
  src/assets/images/si/business_partner3.webp
  src/assets/images/si/business_partner4.webp
  src/components/Main/BusinessPartner.jsx
  src/constants/BUSINESS_PARTNER_CONTENTS.js
Labels: Refactor

#104 [CONE-53] 에스지산업, 자동차환경 회사로고
  src/assets/images/ce/business_partner1.png
  src/assets/images/ce/business_partner1.webp
  src/assets/images/ce/business_partner10.webp
  src/assets/images/ce/business_partner2.webp
  src/assets/images/ce/business_partner3.webp
  src/assets/images/ce/business_partner4.webp
  src/assets/images/ce/business_partner5.webp
  src/assets/images/ce/business_partner6.webp
  src/assets/images/ce/business_partner7.webp
  src/assets/images/ce/business_partner8.webp
  src/assets/images/ce/business_partner9.webp
  src/assets/images/sg/business_partner1.webp
  src/assets/images/sg/business_partner2.webp
  src/assets/images/sg/business_partner3.webp
  src/assets/images/sg/business_partner4.webp
  src/components/Main/SubCategoryBar.jsx
  src/constants/BUSINESS_PARTNER_CONTENTS.js
Labels: Feat
